# Generated by Django 2.0.4 on 2018-06-12 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('v_id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.BigIntegerField()),
                ('date', models.DateTimeField()),
                ('file', models.FileField(default='unknown', upload_to='img/')),
            ],
        ),
        migrations.AddField(
            model_name='user_video',
            name='v_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show_video.Video'),
        ),
    ]
