# Generated by Django 2.0.4 on 2018-06-11 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('v_id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.BigIntegerField()),
                ('date', models.DateTimeField()),
                ('file', models.FileField(default='unknown', upload_to='sql_save/')),
            ],
        ),
        migrations.AddField(
            model_name='user_video',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show_video.Users'),
        ),
        migrations.AddField(
            model_name='user_video',
            name='v_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show_video.Video'),
        ),
    ]
