# Generated by Django 2.0.4 on 2018-06-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(default='unknown', upload_to='img/'),
        ),
    ]
